// format:
// ['player line', 'enemy line', 'player line', ...]
// ['', 'enemy starts', '', 'enemy continues', 'player line', ...]
export const dialogue = {
	start: [
		["I've been angry and sad about things that you do!", 'Then die mad!'],
		["Don't say I didn't warn you!", 'How can I resist this!'],
		[
			'',
			"Looks like you'll never learn!",
			'You play me time and time again...',
			'',
			'AND THAT MAKES ME STRONG!!',
		],
		[
			'You took her heart...',
			'',
			'Now you must pay the price!',
			'I already have...',
		],
		['You betrayed us!', 'Nothing lost and nothing gained!'],
		['', 'You come to look for a king? Here I am!', "I'll never submit!"],
		['', 'Does your mother know?', 'What?', 'That her child is about to die!?'],
		[
			'Do we have to fight?',
			'Battle is but a dance...',
			'',
			'I let the music speak!',
		],
		[
			"We don't have to do this!",
			'',
			'I still have faith in you!',
			'Then you truly are a fool!!',
		],
		['', "I've been waiting for you.", 'What? Why?', 'You... thrill me.'],
		[
			'',
			'How many times will you try and fail!',
			'Mamma mia, here we go again!',
		],
		['One of us...', 'Must die!!'],
		['', 'You think you can win?', 'Take a chance on me!'],
		['', 'You!?!!?', "That's me!"],
		['', 'You dare to challenge me?!', 'The winner takes it all!'],
		[
			'',
			"Just take my hand, I'll show you everything!",
			'',
			'The secrets that my paradise can bring!!',
			'Never!!',
		],
		[
			'',
			"I'm really glad you came.",
			'',
			'You know the stars.',
			'You know the game.',
		],
		["We've done it all before...", "Now we're back to get some more!"],
		[
			'You monster!',
			'Me? What about all those men?',
			'',
			'Sacrificed their lives to lead the way!',
		],
	],
	lose: [
		["No.. I can't...", 'Young and sweet, only seventeen... Such a shame.'],
		[
			'Aarghhh...',
			'A battle won, but the war...',
			'',
			'It goes on and on and on.',
		],
		['Arghhhh!!', '', "I'll never forgive you...", 'Should I laugh or cry!?'],
		['Gah..', '', "Couldn't escape if I wanted to...", 'Wahaha!'],
		['I tried to hold you back..', '', 'But you were stronger...', 'Oh yeah!!'],
		[
			'Graghhh..',
			'',
			'One of these days..',
			'',
			'Gonna teach him a lesson alright...',
		],
		[
			'Kh-guhhh...',
			'The last day is dawning.',
			'',
			'On the darkest of nights, nobody knew how to fight.',
		],
		[
			'You... really.. had the power...',
			'I only saw it as dreams you would weave.',
			'',
			'Until the final hour...',
		],
		['Nyyuhhh...', 'Just a tiny figure.', '', 'Blue eyes, filled with pain.'],
		[
			'Why...',
			'I was sick and tired of everything.',
			'W-what...',
			'Suddenly I feel all right.',
		],
		[
			'H-how...',
			"Child's play.",
			'H-how can anyone..',
			'',
			'Be so lonely...',
			'...',
		],
		['Gyaaa!!', 'Oh, no hard feelings between you and me.'],
		[
			"No.. I won't- gah...",
			'How proud you were to fight for freedom in this land.',
		],
		['Ghhnn...', 'If I had to the same again...', '', 'I would, my friend.'],
		[
			'It used to be so nice!',
			'',
			'It used to be so good!',
			'You have closed your mind.',
		],
		[
			'Aauurhghhh...',
			'Sitting here close to you...',
			'',
			"Maybe tonight, we're through.",
		],
	],
	win: [
		["Bye bye doesn't mean forever!", 'Perhaps it should...'],
		[
			"I didn't want things to end like this...",
			"Please don't talk, go on, play...",
		],
		[
			'',
			'Gahh... From a twinkling star...',
			'What?',
			'To a passing angel.',
			'???',
			'Echoes of a voice I knew...',
		],
		['', 'Ahh..', '', 'I lay my life.. before you...'],
		['', "So close.. it's...", '', 'Slipping.. through my fingers...'],
		['', 'T-thank you..', '', 'For.. the music...'],
		[
			'',
			'Disaster.. and disgrace...',
			'Looks like the king has lost his crown!',
		],
		[
			"It didn't have to be like this!",
			'The grass is mellow... the sky is blue...',
			'',
			'My paradise.. Is waiting...',
		],
		['', 'No regrets...', 'Aha!'],
		['', 'I have met my destiny...', 'You sure have!'],
		[
			'',
			'Nooo!!',
			'When all is said and done...',
			'',
			'Evil will never prevail!',
		],
		["You're finished!", 'Why did it have to be me..'],
		[
			'',
			'Nhhh...',
			'',
			"As long as.. we're together...",
			'...',
			'',
			"As long as we're together.",
		],
		['', 'Hggrg...', '', 'People who fear me.. never come near me...', '...'],
		['', 'No...', '', 'This has been my longest day...'],
	],
	// player hit
	hurt: [
		['', 'Did that hurt? Kyahaha!', "Grr.. It's as good as new!"],
		[
			'Uh oh, shields failing!',
			'Here is where the story ends, this is goodbye!',
		],
		['SOS!!'],
		['', 'Clumsy, like a clown!'],
		['Under attack!!'],
		["Now look what you've done!", '', 'You owe me one!'],
		['All this damage is gonna cost money money money!'],
		['Ahh! These beams are gonna blind me!'],
		["Gah! It isn't nice!"],
		['', 'Like shooting a sitting duck!'],
		['I feel a kind of fear!'],
		['', "There's no escaping now!"],
		['Suddenly the panic takes me!!'],
		["The scars they're leaving..."],
		["You're a doggone beast!!"],
		['', 'Feeling stupid?!', '', 'Feeling SMALL!?!??'],
		["It's not fair!"],
	],
	// enemy hit
	hit: [
		['Please surrender!', 'I would never be such a fool!'],
		["You can't hold out much longer!", "Don't shut me down!"],
		['Watch out!', 'Gr..'],
		['Ha, take that!', "There's no limit to what I feel!!"],
		['For liberty!!'],
		['', 'You put me to the test!'],
		['', 'How lucky can one fellow be?!'],
		['I always find you!'],
		['The wonder of the moment!'],
		['', 'Life is flowing!!'],
	],
	overheat: [
		['Overheated again!?', '', "They didn't last very long..."],
		["The signal's sounding once again!"],
		['Irritation building!'],
		['Too much heat and action!'],
		['Urge to move on!'],
		["Gettin' hot in here..."],
		['Ah! Gotta watch the heat...'],
		['', "What's the matter, can't take the heat!?"],
	],
	// nothing interesting happened for awhile
	delay: [
		['I know that there is no reason for you to linger.', 'Shut up.'],
		['Your father and sister are gone...', 'They deserved better!'],
		[
			"You're grieving deeply but still moving on...",
			"You'll die with the rest of those heartless fools!",
		],
		['I hate to see you like this...', 'Then help me create a new world!'],
		[
			"I'm your best friend!",
			'',
			"I'm the one you must rely on!",
			"You'll never understand!",
		],
		[
			"Down in the street they're all singing and shouting!",
			'Staying alive though the city is dead.',
			'You could save them! You had the power!',
			'They are weak!',
		],
		[
			'',
			"Advanced Bipedal Battle Armour. Fitting, isn't it?",
			'Why?',
			'Battle.',
			'',
			"That's the name of the game!",
		],
		['', "Soon we'll all live in a rich man's world...", '', 'MY WORLD!!!'],
		[
			'Since we were kids, I knew...',
			'',
			'We were always meant to stay together!',
			"I don't need you anymore, I've had enough.",
		],
		['No one else sees it, but I know your tale.', 'Enough!!'],
		['I watched the ship leaving harbor at sunrise.', 'That changes nothing!'],
		['', 'The future is casting a shadow.', '', 'No one else sees it...'],
		['You were crying...', 'Shut up.', 'Alone on your bed-', 'SHUT UP!!'],
		[
			'',
			'They came flying from far away...',
			'What?',
			"Now I'm under their spell.",
			'Who!?',
			'...Nevermind.',
		],
		[
			'We were young!',
			'',
			'And full of life!',
			'And NONE of us prepared to die!!',
		],
		['', 'The city is a nightmare.', '', 'A horrible dream!'],
		[
			'',
			'You should have forgotten me like the rest.',
			"I'll never let you go!",
		],
		[
			'Why did you betray us!?',
			'In time you will understand that the dreams we dreamed...',
			'',
			'Were made of sand!!',
		],
		[
			'',
			'...',
			'',
			'This was just another town.',
			'Give my restless soul a little patience.',
		],
		[
			'',
			"By the time I'm done with you...",
			'',
			'You will have no time for grieving!',
			'ARGHHH!',
		],
		[
			'',
			'GYAHAHAHA!!!',
			"What's wrong with you?",
			'',
			'Is there a hole in your soul?',
		],
	],
};
