// format:
// ['player line', 'enemy line', 'player line', ...]
// ['', 'enemy starts', '', 'enemy continues', 'player line', ...]
export const dialogue = {
	start: [
		["I've been angry and sad about things that you do!", 'Then die mad!'],
		[
			'',
			'You should have forgotten me like the rest.',
			"I'll never let you go!",
		],
		["Don't say I didn't warn you!", 'How can I resist this!'],
		[
			'',
			"Looks like you'll never learn!",
			'You play me time and time again...',
			'',
			'AND THAT MAKES ME STRONG!!',
		],
		[
			'You took her heart...',
			'',
			'Now you must pay the price!',
			'I already have...',
		],
		[
			'Why did you betray us!?',
			'In time you will understand that the dreams we dreamed...',
			'',
			'Were made of sand!!',
		],
		[
			'',
			'...',
			'',
			'This was just another town.',
			'Give my restless soul a little patience.',
		],
		['You betrayed us!', 'Nothing lost and nothing gained!'],
		[
			'',
			"By the time I'm done with you...",
			'',
			'You will have no time for grieving!',
			'ARGHHH!',
		],
		['', 'You come to look for a king? Here I am!', "I'll never submit!"],
		['', 'Does your mother know?', 'What?', 'That her child is about to die!?'],
		[
			'',
			'GYAHAHAHA!!!',
			"What's wrong with you?",
			'',
			'Is there a hole in your soul?',
		],
		[
			'Do we have to fight?',
			'Battle is but a dance...',
			'',
			'I let the music speak!',
		],
		[
			"We don't have to do this!",
			'',
			'I still have faith in you!',
			'Then you truly are a fool!!',
		],
		['', "I've been waiting for you.", 'What? Why?', 'You... thrill me.'],
		[
			'',
			'How many times will you try and fail!',
			'Mamma mia, here we go again!',
		],
		['One of us...', 'Must die!!'],
		['', 'You think you can win?', 'Take a chance on me!'],
		['', 'You!?!!?', "That's me!"],
		['', 'You dare to challenge me?!', 'The winner takes it all!'],
		[
			'',
			"Just take my hand, I'll show you everything!",
			'',
			'The secrets that my paradise can bring!!',
			'Never!!',
		],
		[
			'',
			"I'm really glad you came.",
			'',
			'You know the stars.',
			'You know the game.',
		],
		["We've done it all before...", "Now we're back to get some more!"],
		[
			'You monster!',
			'Me? What about all those men?',
			'',
			'Sacrificed their lives to lead the way!',
		],
	],
	lose: [
		["No.. I can't...", 'Young and sweet, only seventeen... Such a shame.'],
		[
			'Aarghhh...',
			'A battle won, but the war...',
			'',
			'It goes on and on and on.',
		],
		['Arghhhh!!', '', "I'll never forgive you...", 'Should I laugh or cry!?'],
		['Gah..', '', "Couldn't escape if I wanted to...", 'Wahaha!'],
		['I tried to hold you back..', '', 'But you were stronger...', 'Oh yeah!!'],
		[
			'Graghhh..',
			'',
			'One of these days..',
			'',
			'Gonna teach him a lesson alright...',
		],
	],
	win: [
		["Bye bye doesn't mean forever!", 'Perhaps it should...'],
		[
			"I didn't want things to end like this...",
			"Please don't talk, go on, play...",
		],
		[
			'',
			'Gahh... From a twinkling star...',
			'What?',
			'To a passing angel.',
			'???',
			'Echoes of a voice I knew...',
		],
		['', 'Ahh..', '', 'I lay my life.. before you...'],
		['', "So close.. it's...", '', 'Slipping.. through my fingers...'],
		['', 'T-thank you..', '', 'For.. the music...'],
		[
			'',
			'Disaster.. and disgrace...',
			'Looks like the king has lost his crown!',
		],
		[
			"It didn't have to be like this!",
			'The grass is mellow... the sky is blue...',
			'',
			'My paradise.. Is waiting...',
		],
		['', 'No regrets...', 'Aha!'],
		['', 'I have met my destiny...', 'You sure have!'],
		[
			'',
			'Nooo!!',
			'When all is said and done...',
			'',
			'Evil will never prevail!',
		],
		["You're finished!", 'Why did it have to be me..'],
	],
	// player hit
	hurt: [
		['', 'Did that hurt? Kyahaha!', "Grr.. It's as good as new!"],
		[
			'Uh oh, shields failing!',
			'Here is where the story ends, this is goodbye!',
		],
		['SOS!!'],
		['', 'Clumsy, like a clown!'],
		['Under attack!!'],
		["Now look what you've done!", '', 'You owe me one!'],
		['All this damage is gonna cost money money money!'],
	],
	// enemy hit
	hit: [
		['Please surrender!', 'I would never be such a fool!'],
		["You can't hold out much longer!", "Don't shut me down!"],
		['Watch out!', 'Gr..'],
	],
	overheat: [
		["Gettin' hot in here..."],
		['Ah! Gotta watch the heat...'],
		['', "What's the matter, can't take the heat!?"],
	],
	// nothing interesting happened for awhile
	delay: [
		['I know that there is no reason for you to linger.', 'Shut up.'],
		['Your father and sister are gone...', 'They deserved better!'],
		[
			"You're grieving deeply but still moving on...",
			"You'll die with the rest of those heartless fools!",
		],
		['I hate to see you like this...', 'Then help me create a new world!'],
		[
			"I'm your best friend!",
			'',
			"I'm the one you must rely on!",
			"You'll never understand!",
		],
		[
			"Down in the street they're all singing and shouting!",
			'Staying alive though the city is dead.',
			'You could save them! You had the power!',
			'They are weak!',
		],
		[
			'',
			"Advanced Bipedal Battle Armour. Fitting, isn't it?",
			'Why?',
			'Battle.',
			'',
			"That's the name of the game!",
		],
		['', "Soon we'll all live in a rich man's world...", '', 'MY WORLD!!!'],
		[
			'Since we were kids, I knew...',
			'',
			'We were always meant to stay together!',
			"I don't need you anymore, I've had enough.",
		],
	],
};
